### PR TITLE
Added BZip2 and Zlib compression code to project

### PR DESCRIPTION
**Pull request by koliva8245**
Added BZip2 and Zlib compression code to MpqTool project.  Removed SharpZibLib dependency. 

Both these compressions libraries are from dotnetzip and are much faster than SharpZibLib.

### CODE REVIEW

**Comment by barrett777** [comment]
Thanks for putting this together :) I'll try to look into it this weekend

Did you compare these libraries for extracting replay files?

When I Google the two, my first impressions are that some users think dotnetzip is faster for compression, but it doesn't seem to really matter for extracting files

I'll try it out locally either way and see if it's a noticeable improvement

**Comment by koliva8245** [comment]
Yes, I parsed through 100 of my latest replays. It took about ~54 seconds
for sharpziplib while it took only ~32 seconds for dotnetzip.

**Comment by barrett777** [comment]
That would be delightful!  I'll try it out soon

**Comment by barrett777** [comment]
This is good :) Though I'll add it in a separate commit, just using a NuGet package

I personally see ~20% faster replay parsing, which is really great for such low effort

**Comment by koliva8245** [comment]
The reason I added the code files to the project instead of a Nuget package
was because dotnetzip is not compatible with .netstandard.  By adding the
nuget packge, it breaks the .netstandard solution.

**Comment by barrett777** [comment]
Ah I see.  I'd rather not bring in all the files into this project though

The .netstandard project may just need to stick with SharpZipLib.  Maybe the DotNetZip NuGet will support .netstandard in the future

If this is important to you, you'll probably just need to keep these changes in a local branch

**Comment by koliva8245** [comment]
I suppose so.  I'll fix up the .netstandard solution later if you haven't
by then.

**Pull request closed without merging**
